version: '2'
services:
  play:
    build:
      context: ./
      dockerfile: Dockerfile.app
    ports:
     - 31080:80
    working_dir: /var/www
    volumes:
      - /var/www/play.amtgard.com:/var/www/app
    container_name: play
    networks:
      - apps

networks:
  apps: