version: '2'
services:
  go:
    build:
      context: ./
      dockerfile: Dockerfile.app
    ports:
     - 32080:80
    working_dir: /var/www
    volumes:
      - /var/www/go.amtgard.com:/var/www/app
    container_name: go
    networks:
      - apps

networks:
  apps: