version: '2'
services:
  beholder:
    build:
      context: ./
      dockerfile: Dockerfile.app
    ports:
     - 33080:80
    working_dir: /var/www
    volumes:
      - /var/www/beholder.amtgard.com:/var/www/app
    container_name: beholder
    networks:
      - apps

networks:
  apps: